theme: jekyll-theme-minimal
title: "Foundations of 
Bioinformatics Class
(F19)"
logo:http://sdcitybeat.com/downloads/28742/download/ucsd_shutterstock_727007476forweb.jpg?cb=63a67da3d24b55447d8e216a065b1d22&w=1000&h=
