---
title: "Class 7 R function and packages"
author: "Jiawei Xu"
date: "10/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 

```{r}
#source online files
source("http://tinyurl.com/rescale-R")
```

```{r}
rescale(1:10)
```

```{r}
rescale(c(3, 10, NA, 7))
```

```{r}
rescale2 <- function(x, na.rm=TRUE, plot=FALSE, ...) {
if( !is.numeric(x) ) {
stop("Input x should be numeric", call.=FALSE)
}
rng <-range(x, na.rm=na.rm)
answer <- (x - rng[1]) / (rng[2] - rng[1])
if(plot) {
plot(answer, ...)
}
return(answer)
}
```

```{r}
rescale2(c(3, 10, NA, 7))
```
```{r}
x <- c(3, 5, NA, 4, NA)

is.na(x)

which(is.na(x)) # show the order of the NA in the vector
```
```{r}
both_na <- function(x, y) {
sum( is.na(x) & is.na(y) )
}
```

```{r}
x <- c(NA, NA, NA)
y1 <- c( 1, NA, NA)
y2 <- c( 1, NA, NA, NA)
nchar(x)

both_na(x, y1)
both_na(x, y2) # the last element of y2 vector recyles 
```

```{r}
both_na2 <- function(x, y) {
if (length(x) != length(y)){
  stop("Input x and y should be the same length")
}
  sum( is.na(x) & is.na(y) )
}
```

```{r}
# student 1
a <- c(100, 100, 100, 100, 100, 100, 100, 90)
# student 2
b <- c(100, NA, 90, 90, 90, 90, 97, 80)
```

```{r}
grade <- function(x){
  mean(x[-which.min(x)], na.rm = TRUE) # -a[b] will exclude b from a
}
```

```{r}
grade(a)
grade(b)
```


```{r}
install.packages("rgl")
library(rgl)

```
